### PR TITLE
Added transcript highlight feature as audio plays

### PR DESCRIPTION
**Pull request by Harsh15021992**
Issue #105 

Description of changes: 
1. Added transcript highlight feature as audio plays
2. Removed console error of key
3. Added default parameter
4. Added HTML best practices

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rstrahan — CHANGES_REQUESTED** [review]
Hi Harsh, I ran a test with the PR..  Can you take a look at the transcript display on the first sample call (Card2_GUID_102_AGENT_AndrewK_DT_2022-03-22T12-23-49.wav)... The highlighting of ISSUE is getting a bit messed up..  Should look like this:
image
But after applying the PR 111, it looks like this:
image
Thanks!
Bob

**Comment by Harsh15021992** [comment]
> Hi Harsh, I ran a test with the PR.. Can you take a look at the transcript display on the first sample call (Card2_GUID_102_AGENT_AndrewK_DT_2022-03-22T12-23-49.wav)... The highlighting of ISSUE is getting a bit messed up.. Should look like this: image But after applying the PR 111, it looks like this: image Thanks! Bob

Hi Bob,
I have made the changes and issue is fixed.
Kindly review.

**Comment by rstrahan** [comment]
Looks great now.. Thanks for the fix!

**Comment by Harsh15021992** [comment]
Hi Bob,

I have reverted duplicate JSON changes and now using `[WordConfidence]` for text highlighting.

**Comment by rstrahan** [comment]
Thanks Harsh.. Andrew is reviewing now.

**Pull request merged**
